// Alert Types
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
// Register Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
// TOKEN PERSISTANCE/ AUTH VALIDATIOON TYPES
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
// Login Types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'




// Dealer Register Types
export const DEALER_REGISTER_SUCCESS = 'DEALER_REGISTER_SUCCESS'
export const DEALER_REGISTER_FAIL = 'DEALER_REGISTER_FAIL'

// TOKEN PERSISTANCE/ AUTH VALIDATIOON TYPES
export const DEALER_LOADED = 'DEALER_LOADED'

// Dealer Login Types
export const DEALER_LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const DEALER_LOGIN_FAIL = 'LOGIN_FAIL'


// Logout Type
export const LOGOUT = 'LOGOUT'
